# generated by datamodel-codegen:
#   filename:  structuredData.json
#   timestamp: 2024-11-29T00:49:38+00:00

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, Field


class Version(BaseModel):
    json_export: str
    page_segmentation: str
    schema_: str = Field(..., alias="schema")
    structure: str
    table_structure: str


class ExtendedMetadata(BaseModel):
    ID_instance: str
    ID_permanent: str
    has_acroform: bool
    has_embedded_files: bool
    is_XFA: bool
    is_certified: bool
    is_encrypted: bool
    is_digitally_signed: bool
    language: str
    page_count: int
    pdf_version: str
    pdfa_compliance_level: str
    pdfua_compliance_level: str


class FontInfo(BaseModel):
    alt_family_name: str
    embedded: bool
    encoding: str
    family_name: str
    font_type: str
    italic: bool
    monospaced: bool
    name: str
    subset: bool
    weight: int


class Attributes(BaseModel):
    LineHeight: Optional[float] = None
    SpaceAfter: Optional[float] = None
    TextAlign: Optional[str] = None
    Placement: Optional[str] = None
    BBox: Optional[List[float]] = None
    BaselineShift: Optional[float] = None
    TextPosition: Optional[str] = None
    NumCol: Optional[int] = None
    NumRow: Optional[int] = None
    BlockAlign: Optional[str] = None
    BorderColor: Optional[List[Union[Optional[int | float], List[int | float]]]] = None
    BorderStyle: Optional[Union[str, List[str]]] = None
    BorderThickness: Optional[Union[float, List[float]]] = None
    ColIndex: Optional[int] = None
    Height: Optional[float] = None
    InlineAlign: Optional[str] = None
    RowIndex: Optional[int] = None
    Width: Optional[float] = None
    RowSpan: Optional[int] = None
    ColSpan: Optional[int] = None


class Element(BaseModel):
    Bounds: Optional[tuple[float, float, float, float]] = None
    Font: Optional[FontInfo] = None
    HasClip: Optional[bool] = None
    Lang: Optional[str] = None
    ObjectID: int
    Page: Optional[int] = None
    Path: str
    Text: Optional[str] = None
    TextSize: Optional[float] = None
    attributes: Optional[Attributes] = None
    Rotation: Optional[float] = None
    filePaths: Optional[List[str]] = None


class Boxes(BaseModel):
    CropBox: List[float]
    MediaBox: List[float]


class Page(BaseModel):
    boxes: Boxes
    height: float
    is_scanned: bool
    page_number: int
    rotation: int
    width: float


class AdobeStructuredData(BaseModel):
    version: Version
    extended_metadata: ExtendedMetadata
    elements: List[Element]
    pages: List[Page]
